cultureamp/ca-go

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
This PR adds a basic `devcontainer` config to enable local development using VSCode Remote Containers and/or GitHub Codespaces.
> Add Remote Containers config for VSCode/Codespaces

- LICENSE.txt
This repo is public, and requires a license to be properly recognised by the Go tooling (for purposes like documentation generation). The MIT license is sufficient here: there's no need for the code in this repo to be encumbered with the reciprocal clauses provided by the GPL or similar licenses.
> doc: add MIT license

- go.mod
- go.sum
- x/request/doc.go
- x/request/requestids.go
- x/request/requestids_test.go
- x/request/user.go
- x/request/user_test.go
This PR adds a `request` package exposing types and helper functions to create, add, and retrieve request-scoped attributes to context.Context.
There are two sets of attributes that can be unique per request:
- Request identifiers like the trace, correlation, and request IDs.
- User identifiers like their account and user IDs, for authenticated requests.
Both sets may need to be present in the context for certain request middleware to function correctly. An example is the Sentry error reporter, which is provided request and user identifiers where available.
> feat: add request package

- x/launchdarkly/flags/doc.go
- x/launchdarkly/flags/evaluationcontext/doc.go
- x/launchdarkly/flags/evaluationcontext/evaluationcontext.go
- x/launchdarkly/flags/evaluationcontext/user.go
- x/launchdarkly/flags/evaluationcontext/user_test.go
This PR modifies the `flags` package to prefix the keys used in the evaluation context sent to LaunchDarkly. The prefix will be the type of entity represented by the context, for example a `user` or `survey`, and is used to logically distinguish different business entities used in LD for flag targeting.
Along with this change, the PR updates the docs for the `flags` package to fix some whitespace problems. The PR also adds package documentation to `evaluationcontext` as it's a bit of a tricky concept to explain.
> feat: prefix evaluation context keys

- x/launchdarkly/flags/client.go
- x/launchdarkly/flags/config.go
This PR modifies the `flags` package to set a default initWait value of 5 seconds. The initWait value specifies how long the LD client should block while it's waiting to establish an initial connection to LD, and to download the set of flags and rules.
Previously, there was no default and the documentation did not cover that a custom initWait value should be specified. This caused issues where users attempted to query for a flag with a client that had not yet initialised, leading to an error.
5 seconds seems like a sensible default for the kinds of payload sizes we would expect, given the number of flags and rules we would have during the initial rollout. The option always exists to override this value with a custom value.
> fix: set a default init wait time

- catalog-info.yaml
This PR adds a `catalog-info.yaml` at the top level of the repository, to make this project visible in Backstage.
The structure of the YAML was adapted from https://github.com/cultureamp/ca-sgw-ruby/blob/main/catalog-info.yaml
> chore: add catalog entry for Backstage

- x/launchdarkly/flags/config.go
- x/launchdarkly/flags/doc.go
This PR introduces a FromEnvironment() ConfigOption that automatically configures the SDK based on the value of an environment variable. This offers another level of convenience for consumers of the library, and also enables us to roll out configuration changes transparently.
See [this page](https://cultureamp.atlassian.net/wiki/spaces/CoSe/pages/2706016523/Feature+Flags+-+Wrapper+SDKs#Environment-variable) for more context.
> feat: autoconfigure flags SDK from env var

- go.mod
- x/launchdarkly/flags/client.go
- x/launchdarkly/flags/client_test.go
- x/launchdarkly/flags/config.go
- x/launchdarkly/flags/doc.go
- x/launchdarkly/flags/evaluationcontext/user.go
- x/launchdarkly/flags/evaluationcontext/user_test.go
- x/launchdarkly/flags/flags.go
- x/launchdarkly/flags/flags_test.go
The Ruby Wrapper was updated while being used to deploy to prod and some improvements were identified. To match this wrapper, the go wrapper also needs to be updated. This PR changes the following:
- FromEnvironment() should be the default configuration option for a client
- A uuid should be used as the key for an anonymous user rather than a hardcoded string as this allows the targeting of users before they are logged in
- Update unit tests to work with new implementation
Please see the following [PR](https://github.com/cultureamp/ca-feature_flags-ruby/pull/10 - Connect to preview)[https://github.com/cultureamp/ca-feature_flags-ruby/pull/10 - Connect to preview](https://github.com/cultureamp/ca-feature_flags-ruby/pull/10) for the Ruby Wrapper updates
> [COSE-24] Update LD Wrapper to match Ruby Wrapper

- x/launchdarkly/flags/client.go
- x/launchdarkly/flags/client_test.go
- x/launchdarkly/flags/config.go
- x/launchdarkly/flags/doc.go
Modifies how the final configuration for the Proxy and Lambda modes are
constructed so the user is able to supply configuration overrides via
ConfigOption arguments to the NewClient() function. The "base"
configuration is sourced from the LAUNCHDARKLY_CONFIGURATION environment
variable and provides a sensible default for most users. Users with
specific needs can opt to force the client into a specific mode, and
supply relevant configuration overrides for those modes.
For example, the WithProxyMode() function allows the user to specify an
alternate URL for the Relay Proxy (different from the one we specify in
the environment variable). WithLambdaMode() allows the user to configure
the client to connect directly to a DynamoDB table, and customise the
cache TTL and Dynamo base URL as …
> feat: allow config overrides for Proxy and Lambda modes

- .golangci.yml
- go.mod
- go.sum
- x/launchdarkly/flags/client.go
- x/launchdarkly/flags/client_test.go
- x/launchdarkly/flags/config.go
- x/launchdarkly/flags/doc.go
- x/launchdarkly/flags/flags_test.go
This PR enables test mode for the LaunchDarkly SDK. Test mode allows users of the SDK to supply fixed values for flag queries. It's useful for local development, testing, and CI. 
The changes made here allow the SDK to transparently fallback to test mode if the `LAUNCHDARKLY_CONFIGURATION` env var isn't present, or if explicitly told to via the `WithTestMode()` ConfigOption.
> feat: allow the LD client to be configured in test mode

- .github/workflows/pipeline.yml
This didn't work like I thought, the actual checkout is of the base branch. This basically makes sense now, but I didn't understand that at the time.
Changing to simple push for now: another strategy might be needed in the future.
> Use plain push instead of pull_request_target

- .github/workflows/pipeline.yml
Triggers using the `pull_request` event for non-main branches. The `pull_request` event provides the PR URL as one of the event parameters, something Coveralls needs to be able to comment on the PR.
Also, the `COVERALLS_TOKEN` isn't required for the push to work: these are only required for private repos.
> Enable Coveralls comments

- x/sentry/errorreport/errorreport.go
- x/sentry/errorreport/errorreport_test.go
Currently we have to specify a Sentry DSN when running our apps locally. This change allows us to skip the DSN, essentially disabling it:
https://pkg.go.dev/github.com/getsentry/sentry-go#ClientOptions
We do want to avoid accidentally doing this outside of local though, hence the environment check.
> Don't raise when local Sentry DSN missing

- .golangci.yml
- x/sentry/errorreport/config.go
- x/sentry/errorreport/errorreport.go
- x/sentry/errorreport/errorreport_test.go
- x/sentry/errorreport/lambda_example_test.go
- x/sentry/errorreport/mocks_test.go
Enables additional tags to be added as part of initial configuration. These tags will be included in every report, and can be used in Sentry for grouping and searching.
For example, you can add tags singly:
```go
errorreport.WithTag("animal", "gopher"),
```
Or many in one go:
```go
errorreport.WithTags(map[string]string{
"genus":   "phoenicoparrus",
"species": "jamesi",
}),
```
As a side effect, this change stops adding empty values for the build details fields (`farm`, `buildNumber`, `branch`, `commit`). The empty values were being added as a side-effect of using the library, regardless of the intent of the user. Not all processes will use `farm` (a Culture Amp concept), so an empty value will just be unwanted clutter.
> Allow arbitrary tags in error reports

- x/launchdarkly/flags/doc.go
- x/launchdarkly/flags/evaluationcontext/doc.go
- x/launchdarkly/flags/evaluationcontext/evaluationcontext.go
- x/launchdarkly/flags/evaluationcontext/survey.go
- x/launchdarkly/flags/evaluationcontext/survey_test.go
- x/launchdarkly/flags/evaluationcontext/user.go
- x/launchdarkly/flags/evaluationcontext/user_test.go
To get more flexibility out of the platform, our implementation should support evaluation contexts that map to entities other than human users. Some of our use cases revolve around the surveys domain, which can be its own evaluation context and be treated as a first-class citizen of the platform. This means we can target flags against segments of surveys.
In addition to adding survey evaluation context, this also introduces submission of userID and surveyID custom attributes with user and survey contexts respectively in order to provide an easy way of identifying type of context in LaunchDarkly UI.
This PR is consistent with the [Node](https://github.com/cultureamp/ca-launchdarkly-js/pull/68) and [Ruby](https://github.com/cultureamp/ca-launchdarkly-ruby/pull/33) Wrappers
[JIRA …
> COSE-90 Add support for targeting surveys in LaunchDarkly

- x/sarama/kafkaclient/kafka.go
- x/sarama/kafkaclient/kafka_test.go
Currently we only provide a default config which won't work with local Kafka. 
- Added a function to turn on sarama debug log to provide more details when connecting brokers failed
- Added a non-SSL config function to return sarama config that could be used for local Kafka
> add more sarama kafka config options to help testing

- x/sentry/errorreport/errorreport_test.go
- x/sentry/errorreport/filter.go
- x/sentry/errorreport/lambda_example_test.go
Currently the Sentry error titles are pretty general, e.g. `*erros.errorString`. It ends up grouping errors and makes it harder for us to find the latest error in Sentry issues dashboard. We'd like to see what's the actual error from the title.
- Created RootCauseAsTitle which uses error message as custom exception type. 
- Pass it as param of `WithBeforeFilter` on errorreport init.
> [COSE-150] Add custom error report title

- README.md
- x/secrets/doc.go
- x/secrets/secrets.go
- x/secrets/secrets_test.go
This PR extracts our secret fetching code out of the `accounts-service` and `fusionauth-hooks`. We are about to require this logic for the 3rd time, so thought it would be good to extract it out here.
This new package creates the secret manager client for a given region, and fetches the secret value given a secret name.
> [COSE-319] Add secret manager fetching to ca-go.

- x/launchdarkly/flags/config.go
By default, there is no configuration and Big Segments cannot be evaluated. In this
case, any flag evaluation that references a Big Segment will behave as if no users
are included in any Big Segments, and the EvaluationReason associated with any such
flag evaluation will return `ldreason.BigSegmentsStoreNotConfigured` from its
`GetBigSegmentsStatus()` method.
> Add big segments configuration for lambda mode

- x/launchdarkly/flags/client.go
- x/launchdarkly/flags/client_test.go
- x/launchdarkly/flags/config.go
The wrapper is now configured to get Big Segments data from the Relay Proxy persistent storage regardless of the connection mode. In order for us to actually support big segments, we need to connect our clients directly to the data table, and that requires DynamoDB `GetItem` permission on relay table.
> feat: configure big segments and use refined config structure

- x/launchdarkly/flags/evaluationcontext/user.go
- x/launchdarkly/flags/evaluationcontext/user_test.go
Added new anonymous user with subdomain function for web-gateway
Similar to `NewAnonymousUser` function, we would like to capture user subdomain as one custom attribute so that devs can toggle the feature toggle to filter out anonymous user within a particular subdomain (e.g. `qastandard`)
> [core-services] added new anonymous user with subdomain function for web gateway

- x/launchdarkly/flags/client.go
- x/launchdarkly/flags/client_test.go
- x/launchdarkly/flags/config.go
- x/launchdarkly/flags/flags.go
- x/launchdarkly/flags/flags_test.go
We're noticing this is an issue when multiple thread or go-routines accessing the LD client at the same time. 
`runtime error: invalid memory address or nil pointer dereference`
The issue is introduced by LD client (initialising in progress) not ready for serving requests. 
A few improvements are listed below: 
ticket: https://cultureamp.atlassian.net/browse/COSE-476
> [core-services] fix LD initialisation issue

- x/launchdarkly/flags/doc.go
- x/launchdarkly/flags/evaluationcontext/survey.go
- x/launchdarkly/flags/evaluationcontext/survey_test.go
- x/launchdarkly/flags/evaluationcontext/user.go
- x/launchdarkly/flags/evaluationcontext/user_test.go
Enable survey context evaluation for certain accounts based on an account id
> [COSE-398] feat: enable survey context evaluation for certain accounts

- x/vault/auth/aws_iam_auth.go
- x/vault/doc.go
This is because we are using the default STS service in `us-east-1` region
> [COSE-616] Always use `us-east-1` for STS region.

- x/kafka/consumer/consumer.go
- x/vault/vault_decrypter.go
This PR makes the following changes:
- Removes duplicate group name in consumer ID
- Removes decrypt error log from vault decrypter. This was causing a lot of unnecessary noise for "key not found' errors, which are expected when users have been erased.
> chore(decrypter/consumer) fix minor issues

- x/vault/vault_decrypter.go
- x/vault/vault_decrypter_test.go
This is a fix for a panic that occurred in Sentry.
Some investigation revealed that this is probably caused by an edge case we haven't handled where the Vault server responds with a 404 status code and an empty body. In that case a `(nil, nil)` set of return values will be passed up in the library code until it returns in our calling code. Since we're only checking the error, the nil pointer will be dereferenced which causes a panic.
Since this panic happened during a likely leader election in our HA Vault cluster, I think that's _probably_ what happened. But whether or not it is, we'll need to handle this edge case.
* Add explicit field names for the test cases in the table-driven tests for `vault_decrypter`. I was getting confused trying to figure out which field was which.
* Add test …
> fix: handle empty Vault response

- Makefile
- x/kafka/consumer/consumer.go
- x/kafka/consumer/consumer_integration_test.go
- x/kafka/consumer/consumer_test.go
- x/kafka/consumer/example/consumer/main.go
- x/kafka/consumer/example/consumergroup/main.go
- x/kafka/consumer/mock_reader_test.go
- x/kafka/docker-compose.yaml
This PR resolves 2 goroutine data races found in the `consumer` package. 
1. Consumer field `close` is accessed by multiple goroutines when using a `Group`.
2. Unit tests increment a counter from multiple goroutines.
Both of these are of low impact since the the first is only relevant when a Group is being stopped and the second is only only applies to a few unit tests. 
Whats interesting is that an atomic increment is currently being used in the unit tests but this still did not pass the data race check. On the other hand, changing to a mutex based counter did pass the race test.
☘️ Proposed Changes
- Use channels to communicate when a consumer is stopped instead of accessing a shared variable.
- Add type `mutexCounter` to tests which allows a counter to be safely incremented and …
> Fix consumer goroutine data race

- x/kafka/consumer/batching.go
- x/kafka/consumer/consumer.go
The consumer batching implementation resets the `fetched` channel after each batch. This channel contains messages fetched from the Kafka topic.
We do not want to be resetting the `fetched` channel after a batch finishes early because there is no guarantee that it has been fully drained if a new message arrives just as the batch is marked as finished. This is a race condition that can essentially result in a message getting skipped.
We instead never want to reset the `fetched` channel and ensure any left over messages from a previous batch are processed in the current batch.
> Fix consumer fetched message channel reset on batch finish

- x/kafka/consumer/batching.go
Add batchId to consumer debug logs to easily track logs for a particular consumer batch.
> Add batchId to consumer debug logs

- x/kafka/consumer/batching.go
- x/kafka/consumer/consumer.go
- x/kafka/consumer/consumer_integration_test.go
- x/kafka/consumer/consumer_test.go
- x/kafka/consumer/example/consumer/main.go
- x/kafka/kafkatest/test_client.go
The consumer batching early stop condition in the processing loop is currently very inefficient. The stop condition is a sub loop that loops indefinitely whilst locking and unlocking a sync mutex until the stop condition is reached.
A CPU profile test of the consumer batching showed that the stop condition loop used  ~96% of the CPU.
This PR changes the stop condition loop so that it blocks until a new message is available or all current messages have been handled, in which the batch can be stopped early.
This change completely removes the extreme CPU usage.
> Fix consumer batching CPU usage

- x/kafka/consumer/batching.go
- x/kafka/consumer/consumer.go
- x/kafka/consumer/consumer_integration_test.go
- x/kafka/consumer/consumer_test.go
- x/kafka/consumer/options.go
Currently the consumer batch stop condition is done in a manner that aimed to stop the batch in the shortest time possible. This requires a lot of async coordination between the batch fetcher and processor which has ultimately led to intermittent race conditions causing deadlocks. It is possible to fix this within the current early stop condition, however, it would likely result in more cumbersome code all for minimal gains.
The solution to this problem is to simplify the over-engineered code that currently exists. This is achieved by simply using a timer to stop the batch if the batch is not filled to the specified batch size. This will result in the exact same performance for high volumes and will only slightly impact a scenario were consumed events are received in small increments, …
> User timer for consumer batching early stop condition

- x/kafka/consumer/consumer.go
Expose reader batch config fields on `GroupConfig`.
> revision (consumer): expose reader fields in group config

- x/kafka/consumer/consumer.go
- x/kafka/consumer/consumer_test.go
Removing consumer IDs from returned errors in order to prevent high cardinality in error reporting. The consumer ID is also a public field so it is available to the caller if they wish to still use it for reporting.
> chore(consumer): reduce error reporting high cardinality

- .github/workflows/pipeline.yml
We're getting tons of timeouts in the linting stage of our CI.
Since building takes the most time in the linter, doing that beforehand seems to prevent linter timeout.
[COSE-520](https://cultureamp.atlassian.net/browse/COSE-520)
[COSE-520]: https://cultureamp.atlassian.net/browse/COSE-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: prebuild so that linting is faster

- .github/workflows/pipeline.yml
- x/launchdarkly/flags/client_test.go
The local LD tests failed because of missing local aws credentials. After this change, we don't have to rely on local aws credentials for when running local tests
Error is here:
> fix ld tests fail when local not setup aws credentials

- .github/workflows/release.yaml
Introduce a GitHub action pipeline with [anothrNick/github-tag-action](https://github.com/anothrNick/github-tag-action) to automatically increase the patch version of the module when pull requests are merged into the main branch.
> Add github action to bump patch version number on PR merges to main

- cipher/CIPHER.md
- cipher/clients.go
- cipher/kms.go
- cipher/kms_example_test.go
- cipher/kms_test.go
- cipher/package.go
- cipher/package_test.go
Removed the automatic magic that detects if running inside a test and swaps out the implementation for a testRunnerClient.
Updated the CIPHER.md and examples.
> Kms client rework

- log/extensions.go
- log/extensions_test.go
Based on the problems perform-core have had with authorization headers when calling the task-service, we've updated the logging std to include Authorization and XCA headers to the standard logs. 
See: https://cultureamp.atlassian.net/wiki/spaces/TV/pages/3114598406/Logging+Standard#Authorization-fields
This PR adds that support to the logger but adding an extension `WithAuthorizationTracing(req *http.Request)` which adds the "authorization" subdoc and the authz request headers as properties.
> updated logger to support authorization subdoc

- .github/workflows/pipeline.yml
Purpose:
- Prepare for making ca-go INTERNAL
- Remove coveralls for test coverage reporting
- Replaced with gocover-cobertura and gotestfmt.
To Do:
- Use the https://github.com/cultureamp/go-test-coverage action once we have a Go Proxy and ca-go is made INTERNAL
> updated test coverage pipeline tooling

- cipher/client.go
- cipher/client_test.go
- cipher/kms.go
- cipher/kms_test.go
- cipher/package.go
- cipher/package_test.go
Purpose:
- Improve test coverage of the cipher package
- Allow kms.Options (as vararg) so that we can mock the HttpClient and Retryer to by-pass network calls to AWS
> improved cipher test coverage

- log/fields.go
- log/logger.go
- log/package_test.go
- log/properties.go
Purpose: Stop accidental non-compliance of the logging eng std with missing "Properties" for custom log fields.
Currently, this is allowed:
log.Debug("hander_added").Str("resource", "resource_id").Int("test-number", 1).Details("detailed information explain")
But this PR changes this so that the above will no longer compile and force engineers to use:
log.Debug("hander_added").
Properties(log.SubDoc().
Str("resource", "resource_id").
Int("test-number", 1),
).Details("detailed information explain")
> Enforce Properties for custom fields

- jwt/JWT.md
- jwt/jwt_example_test.go
- jwt/package.go
Allow package level default encoder and decoder to be mocked
> Testable JWT package level methods

- .golangci.yml
- log/extensions_test.go
- log/fields.go
Purpose: Cleaned up logging after web-gateway deployment.
Changes:
- Now we don't log empty string values
- Fixed golangci warning "WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. "
> do not log empty Str values

- .github/workflows/pipeline.yml
- .golangci.yml
- .pre-commit-config.yaml
- .tool-versions
- README.md
- go.mod
- go.sum
Purpose: Stay patched and on latest Go version
Changes:
- Updated Go from 1.22.1 to 1.22.2
- Updated dependencies (minus Vault) to latest versions
- Updated Golint to 1.57.2
> Updated to go 1.22.2 and relevant dependencies

- cipher/CIPHER.md
- cipher/client.go
- cipher/kms.go
- cipher/package.go
Changes:
- Updated comments on all public methods
- Encrypt/Decrypt are now all consistently documented across package and instance methods
- Now panic on startup if AWS_REGION not set
- Updated CIPHER.md to reflect AWS_REGION panic
> Cipher comment updates

- jwt/JWT.md
- jwt/decoder.go
- jwt/decoder_options.go
- jwt/encoder.go
- jwt/encoder_options.go
- jwt/package.go
Changes:
- Updated missing or incorrect public comments
- Now panic at startup if missing AUTH_PUBLIC_JWK_KEYS, AUTH_PRIVATE_KEY, or AUTH_PRIVATE_KEY_ID
- Updated JWT.md to reflect this change
> JWT public comment updates

- secrets/SECRETS.md
- secrets/doc.go
- secrets/package.go
Changes:
- Updated SECRETS.md to say we panic if AWS_REGION not set
- Package level startup code now does panic if AWS_REGION not set
> Updated secrets comments and package startup

- jwt/JWT.md
- jwt/claims.go
- jwt/decoder.go
- jwt/jwt_example_test.go
- jwt/package.go
Purpose: To be able to pass in custom claims to the JWT decoder
Changes:
- Added DecodeWithCustomClaims(tokenString string, customClaims jwt.Claims) error 
- Updated JWT.md
> Added support for custom decoded claims

- README.md
- jwt/README.md
- jwt/package.go
- jwt/package_test.go
Purpose: Stop panic at startup for missing env-vars
Changes:
- Removed panics, throw errors when using instead of at startup
- Removed isTestMode
- Package level tests now load test keys (rather than rely on startup to do it)
- Renamed JWT.md to README.md and updated with the latest updates
> JWT: no longer panic at start up for package level  default encoder/decoder

- .github/workflows/pipeline.yml
- .golangci.yml
- launchdarkly/client.go
- log/config.go
- log/config_test.go
- log/logger.go
- log/properties.go
- sentry/examples_test.go
Purpose: Stop panics (very rude) and instead return errors so that clients can handle if they wish.
Changes:
- Send, Details and Detailsf all return error
- Removed mustProcess() and the panic
- Updated comments
- Fixed golint warning about unknown "skip-pkg-cache" setting
> Log Package: return error on Details and Send instead of panic

- .golangci.yml
- go.mod
- go.sum
- log/fields.go
- log/properties_test.go
Purpose: 
- Compliance with the Logging Standard
-  https://cultureamp.atlassian.net/wiki/spaces/TV/pages/3114598406/Logging+Standard#Custom-fields
Changes:
- Added reference to github.com/sosodev/duration to support ISO8601 parsing and formatting
- Changed fields.Duration to covert time.duration to ISO8601 Duration string
> Log Package: time.durations now use ISO8601 format as per logging std

- .github/workflows/pipeline.yml
- .tool-versions
- README.md
- go.mod
Purpose: Close out security issues CVE-2024-24787 and CVE-2024-24788 in Go 1.22.2 
Changes:
- Updated go.mod, tool version and GH pipeline to 1.22.3
> Upgraded Go to 1.22.3 to close CVE-2024-24787 and CVE-2024-24788

- .golangci.yml
- jwt/README.md
- jwt/decoder.go
- jwt/decoder_options.go
- jwt/decoder_options_test.go
- jwt/jwt_example_test.go
- jwt/package.go
- jwt/package_test.go
Purpose: Allow clients to enforce matching aud, iss and sub claims
Changes:
- created DecoderParserOptions with MustMatchAudience, MustMatchIssuer and MustMatchSubject methods
- updated jwt/README.md
> Package JWT: allow clients to optionally enforce matching of aud, iss and sub claims

- .golangci.yml
- jwt/README.md
- jwt/decoder.go
- jwt/decoder_test.go
Purpose: Support the current Decode behaviour for decoding tokens without a "kid" to mean "web-gateway"
Changes:
- Updated Decoder.go to assume kid="web-gateway" if there is no kid in the token.
- Updated tests
- Updated README to explain what happens where there is no "kid" header in the token.
> Package JWT: Support current Decode behaviour for missing kid in the token

- .github/workflows/pipeline.yml
- .tool-versions
- go.mod
From https://go.dev/doc/devel/release:
- go1.22.4 (released 2024-06-04) includes security fixes to the archive/zip and net/netip packages, as well as bug fixes to the compiler, the go command, the linker, the runtime, and the os package. 
- See the [Go 1.22.4 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.4+label%3ACherryPickApproved) on our issue tracker for details.
> Upgrade to Go 1.22.4

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .envrc
- .gitignore
- .pre-commit-config.yaml
- README.md
- devbox.json
- devbox.lock
Adds devbox as the means for setting up the projects locally.
- **Add note about go@1.22.4**
- **Add .env.local to .gitignore and add loading of .env.local to .envrc**
- **Remove .envrc from .gitignore**
- **Run `devbox generate direnv`**
- **Add devbox.json**
- **Devbox add pre-commit, snyk, trufflehog**
- **Exclude devbox.json from check-json commit hook**
- **Update README.md with instructions for setting up with devbox.**
- **Remove .devcontainer config**
- **Remove .tool-versions**
- Check out this branch and review the new [readme instructions](https://github.com/cultureamp/ca-go/tree/add-devbox?tab=readme-ov-file#installation-and-running-with-devbox).
- After running the `devbox run setup` command ensure that you can develop on the project as expected.
This cleans up other means …
> add devbox

- devbox.json
- devbox.lock
Which matches the version bumped to in this commit:
https://github.com/cultureamp/ca-go/commit/6693b1a958170c766e4c5fb9438acc8330e0fcdf
> Update devbox installed go to 1.22.5
